backend:
  name: git-gateway
  branch: main

media_folder: "/static/img"
public_folder: "/img"

logo_url: https://www.theworks.info/images/theworks-black.png

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "date" }
      - { name: "tags", label: "Tags", widget: "select", multiple: true, options: ["Web", "UIUX", "Merch", "Logo", "Branding", "Frontend", "Fonts", "Case study", "Web3"] }
      - { name: "highlight", label: "Highlight", widget: "select", required: false, options: ["Primary", "Web", "UIUX", "Merch", "Logo", "Branding", "Frontend", "Fonts", "Case study", "Web3"] }
      - { name: "preview", label: "Preview", widget: "string" }
      - { name: "image-preview", label: "Preview Image", widget: "image", required: false}
      - { name: "video-preview", label: "Preview Video", widget: "file", required: false}
      - { name: "image_hero", label: "Hero Image", widget: "image", required: false }
      - { name: "what", label: "The What", widget: "string", required: false }
      - { name: "how", label: "The How", widget: "string", required: false }
      - { name: "challenges", label: "Challenges", widget: "string", required: false }
      - { name: "minutes", label: "Minutes to read", widget: "number", value_type: "int" }
      - { name: "body", label: "Body", widget: "markdown", required: false}

  - name: "testimonials"
    label: "Testimonials"
    folder: "src/testimonials"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "text", label: "Text", widget: "string" }
      - { name: "name", label: "Name", widget: "string" }
      - { name: "position", label: "Position", widget: "string" }
      - { name: "affiliation", label: "Affiliation", widget: "string" }
      - { name: "icon", label: "Icon", widget: "image"}


